### ISSUE TITLE
RTX3090 @ driver 471.68

### ISSUE THREAD

**Issue by IordX** [foucault/nvfancontrol#36]
C:\test>nvfancontrol.exe>log.log
INFO - Loading configuration file: "C:\\Users\\Admin\\AppData\\Roaming\\nvfancontrol.conf"
INFO - NVIDIA driver version: 471.68
INFO - NVIDIA graphics adapter #0: NVIDIA GeForce RTX 3090
WARN - Could not get GPU cooler indices or unsupported OS
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "NvAPI_GPU_GetCoolerSettings() failed; error -104"', src\main.rs:715:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "NvAPI_GPU_GetCoolerSettings() failed; error -104"', src\main.rs:84:30
stack backtrace:
   0:     0x7ff6acd4eeae - <unknown>
   1:     0x7ff6acd657eb - <unknown>
   2:     0x7ff6acd48b98 - <unknown>
   3:     0x7ff6acd51d9d - <unknown>
   4:     0x7ff6acd51804 - <unknown>
   5:     0x7ff6acd526ae - <unknown>
   6:     0x7ff6acd521d1 - <unknown>
   7:     0x7ff6acd4f80f - <unknown>
   8:     0x7ff6acd52129 - <unknown>
   9:     0x7ff6acd63600 - <unknown>
  10:     0x7ff6acd63433 - <unknown>
  11:     0x7ff6acd04054 - <unknown>
  12:     0x7ff6acd0efb6 - <unknown>
  13:     0x7ffb24d31030 - <unknown>
  14:     0x7ffb24d34a52 - is_exception_typeof
  15:     0x7ffb24d3e7f4 - _C_specific_handler
  16:     0x7ffb24d33cc8 - is_exception_typeof
  17:     0x7ffb24d3f131 - _CxxFrameHandler3
  18:     0x7ffb3f4f21ff - _chkstk
  19:     0x7ffb3f480939 - RtlUnwindEx
  20:     0x7ffb24d3ecbe - _C_specific_handler
  21:     0x7ffb24d32955 - is_exception_typeof
  22:     0x7ffb24d32d81 - is_exception_typeof
  23:     0x7ffb24d33dc4 - is_exception_typeof
  24:     0x7ffb24d3f131 - _CxxFrameHandler3
  25:     0x7ffb3f4f217f - _chkstk
  26:     0x7ffb3f4a1454 - RtlRaiseException
  27:     0x7ffb3f4a11a5 - RtlRaiseException
  28:     0x7ffb3ccb4ed9 - RaiseException
  29:     0x7ffb24d36220 - CxxThrowException
  30:     0x7ff6acd57a11 - <unknown>
  31:     0x7ff6acd57999 - <unknown>
44  32:     0x7ff6acd52768 - <unknown>
  33:     0x7ff6acd52744 - <unknown>
  34:     0x7ff6acd521d1 - <unknown>
  35:     0x7ff6acd4f80f - <unknown>
  36:     0x7ff6acd52129 - <unknown>
  37:     0x7ff6acd63600 - <unknown>
  38:     0x7ff6acd63433 - <unknown>
  39:     0x7ff6acd0a7cd - <unknown>
  40:     0x7ff6acd0fef6 - <unknown>
  41:     0x7ff6acd0ff2c - <unknown>
  42:     0x7ff6acd52864 - <unknown>
  43:     0x7ff6acd0f5d7 - <unknown>
  44:     0x7ff6acd6c160 - <unknown>
  45:     0x7ffb3d4d7034 - BaseThreadInitThunk
  46:     0x7ffb3f4a2651 - RtlUserThreadStart
thread panicked while panicking. aborting.

C:\test>ver

Microsoft Windows [Version 10.0.19042.1165]

any idea what can be wrong ?

**Comment by foucault** [comment]
Hello! Probably the version of the NVAPI the program is compiled with is not new enough to support 30xx. I'll put out a new build for you to test later today.

14 Aug 2021 02:09:03 IordX ***@***.***>:

**Comment by foucault** [comment]
Can you try this one please?

[nvfancontrol.zip](https://github.com/foucault/nvfancontrol/files/6986474/nvfancontrol.zip)

**Comment by IordX** [comment]
tested , all same

**Comment by foucault** [comment]
That's strange. Can you please run the attached with extra output enabled (`nvfancontrol -d`) and paste the output? I don't need the full stack backtrace just up to the point it crashes.
And a couple of questions:

(1) What's the model of your card? Is it an FE or an other implementation?
(2) Have you tried driver version ≤ 470? Does it work then? If yes, can you rollback to 470, run `nvfancontrol -d` and paste the output?

[nvfancontrol.zip](https://github.com/foucault/nvfancontrol/files/6986818/nvfancontrol.zip)

**Comment by IordX** [comment]
AORUS GeForce RTX™ 3090 XTREME 24G , 3 fans

https://github.com/foucault/nvfancontrol/files/6986818/nvfancontrol.zip
detected as virus and auto deleted
Trojan:Script/Wacatac.B!ml

retested the https://github.com/foucault/nvfancontrol/files/6986474/nvfancontrol.zip again with -d , same driver 471.68

C:\test\nvfancontrol -d
INFO - Loading configuration file: "C:\\Users\\Admin\\AppData\\Roaming\\nvfancontrol.conf"
DEBUG - Curve points: [(40, 50), (50, 60), (60, 60), (70, 70), (80, 80)]
INFO - NVIDIA driver version: 471.68
INFO - NVIDIA graphics adapter #0: NVIDIA GeForce RTX 3090
INFO -   GPU #0 coolers: COOLER-0, COOLER-1
ERROR - Could not update fan speed: NvAPI_GPU_SetClientFanCoolersControl() failed; error -137
DEBUG - GPU #0 Temp: 41; Speed: [0, 0] RPM ([0, 0]%); Load: 0%; Mode: Auto
ERROR - Could not update fan speed: NvAPI_GPU_SetClientFanCoolersControl() failed; error -137
DEBUG - GPU #0 Temp: 41; Speed: [0, 0] RPM ([0, 0]%); Load: 0%; Mode: Auto
ERROR - Could not update fan speed: NvAPI_GPU_SetClientFanCoolersControl() failed; error -137
DEBUG - GPU #0 Temp: 41; Speed: [0, 0] RPM ([0, 0]%); Load: 1%; Mode: Auto
ERROR - Could not update fan speed: NvAPI_GPU_SetClientFanCoolersControl() failed; error -137
DEBUG - GPU #0 Temp: 41; Speed: [0, 0] RPM ([0, 0]%); Load: 1%; Mode: Auto
ERROR - Could not update fan speed: NvAPI_GPU_SetClientFanCoolersControl() failed; error -137
DEBUG - GPU #0 Temp: 41; Speed: [0, 0] RPM ([0, 0]%); Load: 1%; Mode: Auto
ERROR - Could not update fan speed: NvAPI_GPU_SetClientFanCoolersControl() failed; error -137
DEBUG - GPU #0 Temp: 41; Speed: [0, 0] RPM ([0, 0]%); Load: 0%; Mode: Auto
DEBUG - Interrupt signal
DEBUG - Exiting
DEBUG - Resetting fan control
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "NvAPI_GPU_SetClientFanCoolersControl() failed; error -137"', src\main.rs:82:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

stopped with CTRL+C

**Comment by IordX** [comment]
now tested the https://github.com/foucault/nvfancontrol/files/6986818/nvfancontrol.zip 
driver 471.68

C:\test\nvfancontrol.exe -d
INFO - Loading configuration file: "C:\\Users\\i7-8700K\\AppData\\Roaming\\nvfancontrol.conf"
DEBUG - Curve points: [(40, 50), (50, 60), (60, 60), (70, 70), (80, 80)]
INFO - NVIDIA driver version: 471.68
INFO - NVIDIA graphics adapter #0: NVIDIA GeForce RTX 3090
INFO -  Adapter #0 is an RTX card; using newer NvAPI calls
INFO -   GPU #0 coolers: COOLER-0, COOLER-1
ERROR - Could not update fan speed: NvAPI_GPU_SetClientFanCoolersControl() failed; error -137
DEBUG - GPU #0 Temp: 40; Speed: [0, 0] RPM ([0, 0]%); Load: 1%; Mode: Auto
DEBUG - 2 seconds elapsed since fan was last on
ERROR - Could not update fan speed: NvAPI_GPU_SetClientFanCoolersControl() failed; error -137
DEBUG - GPU #0 Temp: 39; Speed: [0, 0] RPM ([0, 0]%); Load: 0%; Mode: Auto
DEBUG - 4 seconds elapsed since fan was last on
ERROR - Could not update fan speed: NvAPI_GPU_SetClientFanCoolersControl() failed; error -137
DEBUG - GPU #0 Temp: 39; Speed: [0, 0] RPM ([0, 0]%); Load: 0%; Mode: Auto
ERROR - Could not update fan speed: NvAPI_GPU_SetClientFanCoolersControl() failed; error -137
DEBUG - GPU #0 Temp: 40; Speed: [0, 0] RPM ([0, 0]%); Load: 1%; Mode: Auto
DEBUG - 2 seconds elapsed since fan was last on
ERROR - Could not update fan speed: NvAPI_GPU_SetClientFanCoolersControl() failed; error -137
DEBUG - GPU #0 Temp: 39; Speed: [0, 0] RPM ([0, 0]%); Load: 1%; Mode: Auto
DEBUG - Interrupt signal
DEBUG - Exiting
DEBUG - Resetting fan control
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "NvAPI_GPU_SetClientFanCoolersControl() failed; error -137"', src\main.rs:82:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

stopped with CTRL+C

**Comment by foucault** [comment]
Obviously it's not a virus, if you're using the built-in windows 10 antivirus it is overeager to delete things and it's only [getting](https://old.reddit.com/r/sysadmin/comments/oof29b/windows_defender_july_update_will_delete/) [worse](https://github.com/qbittorrent/qBittorrent/issues/14489). There's really not much I can do about it, sorry :disappointed: 

Error -137 means [insufficient permissions](https://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/group__nvapistatus.html#gga12534f3b520256799842c0172e9afdf7a8cd0fb381bf16e407251620d83282917). I believe there have been some changes wrt permissions during the last driver iterations. Can you trying running with elevated privileges?

**Comment by IordX** [comment]
admin rights worked , looks like 2 fans supported now , there is anyway to show/support all 3 ?

**Comment by IordX** [comment]
btw tool can search for nvfancontrol.conf in exe folder and use it if found ? (  tested it won't see it now )
nvfancontrol.conf working like a curve , any option to lock fan speed on specific number and just quit ?
if have more than one gpu just execute it 2 times ? , nvfancontrol.exe -g 0 and nvfancontrol.exe -g 1 ? in two CMDs

**Comment by foucault** [comment]
Yay! Good to know it worked. I'm not sure why you're seeing only 2 coolers. Assuming there are set up in 2 clockwise - 1 anticlockwise configuration the two clockwise fans might be tied to a single fan controller. So one of the coolers listed might actually be 2 real fans. That's purely speculation though, as I have no means to check. You can, however, see if all three fans actually work when the curve is active. For a second GPU a second instance should handle the second with the `-g` switch. I'll add multi-gpu functionality on the daemon itself later but there are other things that need fixing first.

Unfortunately there's no way to set and forget at the moment but it's a good idea. I'll see if I can implement it at some point.

**Comment by IordX** [comment]
`Unfortunately there's no way to set and forget at the moment but it's a good idea`

nvfancontrol.exe -g 0 -set 85

something like this maybe , so it will stack at 85% speed and app will just close . nvfancontrol.exe -g all -set 85 , and all for all cards ?

and option to search for nvfancontrol.conf in exe folder will be nice , or get curve input from a cmd line when exe executed , in one line .

thanks
